const MAIN_COLOR = '#8bb174'
const MAIN_COLOR_LIGHT = '#b5ca8d'
const SECOND_COLOR = '#222e50'
const SECOND_COLOR_LIGHT= '#426b69'
const THIRD_COLOR = '#2a4849'

export {MAIN_COLOR, MAIN_COLOR_LIGHT, SECOND_COLOR, SECOND_COLOR_LIGHT, THIRD_COLOR}